### ISSUE TITLE
Rate Limiter

### ISSUE THREAD

**Issue by AnthonyFJGarner** [cryptarbitrage-code/deribit-perpetual-funding#1]
No module named 'ratelimiter'
Where is the rate limiter py file?
Also what is the correct URL? I believe there is no endpoint on
https://history.deribit.com 
for url = "/api/v2/public/get_funding_rate_history"
and 
'https://www.deribit.com' only gives one month of data?

**Comment by AnthonyFJGarner** [comment]
OK, found ratelimiter on pip / PyPI

**Comment by cryptarbitrage-code** [comment]
Correct, ratelimiter is a separate library that needs to be imported, rather than another file in the project.

The endpoint used in this program is either https://test.deribit.com/api/v2/public/get_funding_rate_history for the testnet, or https://www.deribit.com/api/v2/public/get_funding_rate_history for production.
Only 1 month of data is pulled per api call, so there is a loop to call each required month one at a time. This is also why the ratelimiter is used, to stop the api calls going over the Deribit api rate limits.
